import Footer from "@/components/sections/Footer";
import Header from "@/components/sections/Header";
import localFont from "next/font/local";
import "./globals.css";

const quahon = localFont({
  src: [
    {
      path: "./assets/fonts/Quahon.otf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-quahon",
});

const dm = localFont({
  src: [
    {
      path: "./assets/fonts/DMSerifDisplay-Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-dm",
});

export const metadata = {
  title: "Les Chandelles",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${quahon.variable} ${dm.variable} overflow-x-hidden`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
