import { DM_Serif_Display } from 'next/font/google'
import localFont from "next/font/local";
import Header from '@/components/sections/Header'
import Footer from '@/components/sections/Footer'
import './globals.css'


const quahon = localFont({
  src: [
    {
      path: "./assets/fonts/Quahon.otf",
      weight: "400",
      style: "normal",
    },
    
  ],variable: "--font-quahon",});
const dm = DM_Serif_Display({ subsets: ['latin'], weight: ["400"], variable: "--font-dm", });

export const metadata = {
  title: 'Les Chandelles',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={`${quahon.variable} ${dm.variable} overflow-x-hidden`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
